# Generated by Django 4.1.1 on 2022-09-25 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='video',
            field=models.FileField(null=True, upload_to='Tutorials', verbose_name=''),
        ),
    ]
