# Generated by Django 4.1.1 on 2022-09-25 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0003_alter_tutorial_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='video',
            field=models.FileField(null=True, upload_to='tutorial/static/video', verbose_name=''),
        ),
    ]
