# Generated by Django 4.1.1 on 2022-09-25 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('knowledge_base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCollab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('techStack', models.CharField(max_length=50)),
                ('contributos', models.CharField(max_length=100)),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowledge_base.user')),
            ],
        ),
    ]
