# Generated by Django 4.1.1 on 2022-09-26 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectcollab',
            old_name='contributos',
            new_name='contributors',
        ),
    ]
